* converted several quicks to `go`s reorganizing ui changed deps.sh

diff --git a/make/go/go b/make/go/go
--- a/make/go/go
+++ b/make/go/go
@@ -30,7 +30,10 @@ function use_file {
 function find_project_root {
 	_pwd="$(pwd)"
 	cd "$(dirname "${0}")"
-	git rev-parse --show-toplevel
+	git rev-parse --show-toplevel || {
+		echo "failed to find project root"
+		echo "is git installed?"
+		return 1 ;}
 	cd "$_pwd" ;} 
 function find_temp_path {
 	use_coreutils && tmp_path="$temp/$(date +%s)" && [ ! -e "$tmp_path" ] && {
@@ -43,12 +46,9 @@ function fail {
 	eval $@
 	exit 1 ;}
 
-use_coreutils || {
-	exit 1 
-} && {
-	pwd="$(pwd)"
-	root="$(find_project_root)"
-	temp="$root/temp" ;}
+pwd="$(pwd)"
+root="$(find_project_root || exit)"
+temp="$root/temp"
 function as_make {
 	if [ "$#" -ne 2 ]; then
 		echo "$(basename "$(dirname ${0})") <source> <out>"
diff --git a/quick/install b/quick/install
--- a/quick/install
+++ b/quick/install
@@ -1,97 +1,146 @@
 #!/usr/bin/env bash
 
-if [[ `uname` == 'Darwin' ]]; then
-	echo checking gnu tools...
-	command -v brew > /dev/null || { 
-		echo please install homebrew then try again; 
-		echo see https://github.com/Homebrew/install;
-		exit 1;
-	}
-	brew install coreutils
-	#brew install binutils
-	#brew install diffutils
-	#brew install ed --with-default-names
-	#brew install findutils --with-default-names
-	#brew install gawk
-	#brew install gnu-indent --with-default-names
-	#brew install gnu-sed --with-default-names
-	#brew install gnu-tar --with-default-names
-	#brew install gnu-which --with-default-names
-	#brew install gnutls
-	brew install grep --with-default-names
-	#brew install gzip
-	#brew install screen
-	#brew install watch
-	#brew install wdiff --with-gettext
-	#brew install wget
-	PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"
+function use_deps {
+	cd "$root/source/meta/quick/install" ;}
+function use_coreutils {
+	if [[ `uname` == 'Darwin' ]]; then
+		[ -d "/usr/local/opt/coreutils/libexec/gnubin" ] || {
+			echo "coreutils not found"
+			return 1 
+		} && PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH" ;fi }
+function use_node {
+	use_node_bare || {
+		return 1 
+	} && if [ -f "$(dirname $(npm root))/package.json" ]; then
+		[ -d "$(npm root)" ] || {
+			#TODO: does not cover case of empty dependencies
+			echo "node modules not installed"
+			return 1 ;} fi ;}
+function use_node_bare {
+	. ~/.nvm/nvm.sh --no-use
+	nvm use 10 > /dev/null
+	[[ "$(node --version)" == "v10"* ]] || {
+		echo "couldn't change to node v10"
+		return 1 ;} }
+function use_file {
+	[ -f "$1" ] || {
+		echo "$1 doesn't exist"
+		return 1 ;} }
+
+function find_project_root {
+	_pwd="$(pwd)"
+	cd "$(dirname "${0}")"
+	git rev-parse --show-toplevel || {
+		echo "failed to find project root"
+		echo "is git installed?"
+		return 1 ;}
+	cd "$_pwd" ;} 
+function find_temp_path {
+	use_coreutils && tmp_path="$temp/$(date +%s)" && [ ! -e "$tmp_path" ] && {
+		echo "$tmp_path"
+	} || {
+		echo "failed to find temp path"
+		exit 1 ;} }
+
+function fail {
+	eval $@
+	exit 1 ;}
+
+pwd="$(pwd)"
+root="$(find_project_root || exit)"
+temp="$root/temp"
+
+use_deps || {
+	iecho "please compile $root/source/meta/quick/install"
+	exit 1
+} && {
+	if [[ `uname` == 'Darwin' ]]; then
+		echo checking gnu tools...
+		command -v brew > /dev/null || { 
+			echo please install homebrew then try again; 
+			echo see https://github.com/Homebrew/install;
+			exit 1;
+		}
+		brew install coreutils
+		#brew install binutils
+		#brew install diffutils
+		#brew install ed --with-default-names
+		#brew install findutils --with-default-names
+		#brew install gawk
+		#brew install gnu-indent --with-default-names
+		#brew install gnu-sed --with-default-names
+		#brew install gnu-tar --with-default-names
+		#brew install gnu-which --with-default-names
+		#brew install gnutls
+		brew install grep --with-default-names
+		#brew install gzip
+		#brew install screen
+		#brew install watch
+		#brew install wdiff --with-gettext
+		#brew install wget
+		PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"
+		echo
+		echo ;fi
+
+	echo checking nvm version...
+	[ -e ~/.nvm/nvm.sh ] || {
+		echo please install nvm then try again;
+		echo see https://github.com/creationix/nvm#installation;
+		exit 1
+	} && . ~/.nvm/nvm.sh --no-use
+	nvm install 8 && \
+	nvm alias node 8 && \
+	nvm alias default 8
+	nvm use 8
 	echo
 	echo
-fi
 
-echo checking nvm version...
-[ -e ~/.nvm/nvm.sh ] || {
-	echo please install nvm then try again;
-	echo see https://github.com/creationix/nvm#installation;
-	exit 1;
-} && . ~/.nvm/nvm.sh --no-use
-nvm install 8 && \
-nvm alias node 8 && \
-nvm alias default 8
-nvm use 8
-echo
-echo
+	echo checking npm version...
+	if ! npm outdated -g npm | grep -z npm; then
+	    echo npm is up to date
+	else
+	    echo trying to update npm...
+	    npm install -g npm ;fi
+	echo
+	echo
 
-echo checking npm version...
-if ! npm outdated -g npm | grep -z npm; then
-    echo npm is up to date
-else
-    echo trying to update npm...
-    npm install -g npm
-fi
-echo
-echo
-
-echo checking ama...
-if npm list -g ama; then
-    echo ama already installed
-else
-    echo trying install ama...
-    npm install -g jade-ama
-fi
-echo
-echo
+	echo checking ama...
+	if npm list -g ama; then
+	    echo ama already installed
+	else
+	    echo trying install ama...
+	    npm install -g jade-ama ;fi
+	echo
+	echo
 
 
-echo checking cordova...
-if npm list -g cordova@8.0.0; then
-    echo cordova already installed
-else
-    echo trying install cordova...
-    npm install -g cordova@8.0.0
-fi
-echo
-echo
+	echo checking cordova...
+	if npm list -g cordova@8.0.0; then
+	    echo cordova already installed
+	else
+	    echo trying install cordova...
+	    npm install -g cordova@8.0.0 ;fi
+	echo
+	echo
 
 
 
 
-cd "$(dirname "$0")"
-cd "$(git rev-parse --show-toplevel)"
+	cd "$(dirname "$root/source/meta/quick/install")"
+	cd "$(git rev-parse --show-toplevel)"
 
-find . -name package.json
-echo installing npm packages...
-find . -not -regex .*/node_modules/.* -name package.json -exec bash -c 'for f; do git check-ignore -q "$f" || echo "$f"; done' {} + | while read f; do
-	pushd "$(dirname "$f")"
-	npm install
-	ln -s ../ node_modules/__ 2> /dev/null
-	popd
-done
-echo
-echo
+	find . -name package.json
+	echo installing npm packages...
+	find . -not -regex .*/node_modules/.* -name package.json -exec bash -c 'for f; do git check-ignore -q "$f" || echo "$f"; done' {} + | while read f; do
+		pushd "$(dirname "$f")"
+		npm install
+		ln -s ../ node_modules/__ 2> /dev/null
+		popd ;done
+	echo
+	echo
 
 
-echo refreshing amas...
-./quick/refresh
-echo
-echo
+	echo refreshing amas...
+	./quick/refresh
+	echo
+	echo ;}
