checkpoint now we have make/make, make/go, make/ni. make/ni confirms this sort of works

diff --git a/make/go/go b/make/go/go
--- a/make/go/go
+++ b/make/go/go
@@ -1,13 +1,7 @@
 #!/usr/bin/env bash
-function usage {
-	echo "$(basename "$root/source/meta/make/go") <source> <out>" ;}
-if [ "$#" -ne 2 ]; then
-	echo "$(usage)"
-	exit 1 ;fi
-
 
 function use_deps {
-	cd "$(dirname "$root/source/meta/make/go")" ;}
+	cd "$root/source/meta/make/go" ;}
 function use_coreutils {
 	if [[ `uname` == 'Darwin' ]]; then
 		[ -d "/usr/local/opt/coreutils/libexec/gnubin" ] || {
@@ -34,27 +28,43 @@ function use_file {
 		return 1 ;} }
 
 function find_project_root {
-	git rev-parse --show-toplevel; } 
+	_pwd="$(pwd)"
+	cd "$(dirname "${0}")"
+	git rev-parse --show-toplevel
+	cd "$_pwd" ;} 
+function find_temp_path {
+	use_coreutils && tmp_path="$temp/$(date +%s)" && [ ! -e "$tmp_path" ] && {
+		echo "$tmp_path"
+	} || {
+		echo "failed to find temp path"
+		exit 1 ;} }
 
-use_coreutils || {
+function fail {
+	eval $@
 	exit 1 ;}
 
-bare_source="${1%/}"
-bare_out="${2%/}"
-
-source="$(readlink -m "$bare_source")"
-out="$(readlink -m "$bare_out")"
-
-cd "$(dirname "${0}")"
-root="$(find_project_root)"
-use_deps || {
-	echo "please compile $root/source/meta/make/go"
-	exit 1 
-} && use_coreutils || {
-	exit 1 
-} && use_file "$source/go" || {
+use_coreutils || {
 	exit 1 
 } && {
+	pwd="$(pwd)"
+	root="$(find_project_root)"
+	temp="$root/temp" ;}
+function as_make {
+	if [ "$#" -ne 2 ]; then
+		echo "$(basename "$(dirname ${0})") <source> <out>"
+		exit 1 ;fi
+
+	_pwd="$(pwd)"
+	cd "$pwd"
+	source="$(readlink -m "${1%/}")"
+	out="$(readlink -m "${2%/}")"
+	cd "$_pwd" ;}
+use_deps && as_make $@ || {
+	echo "please compile $root/source/meta/make/go"
+	exit 1 
+} && use_coreutils || (fail
+) && use_file "$source/go" || (fail
+) && {
 	mkdir -p "$out" && rm -r "$out/*" 2> /dev/null
 	cp "$source/go" "$out/go"
 
@@ -108,7 +118,7 @@ $(cat "$out/go")" > "$out/go" ;}
 		elif [[ -n $forward_part ]]; then
 		    result="${forward_part:1}" ;fi
 
-		echo $result; }
+		echo $result ;}
 
 	source_from_root="$(rel_path "$root" "$source")"
 	source_rel_path='$root/'"$source_from_root"
@@ -117,6 +127,4 @@ $(cat "$out/go")" > "$out/go" ;}
 
 	sed -i 's|$''0|'"$source_rel_path"'|g' "$out/go"
 
-	} || {
-	echo "failed to make go of $source"
-	exit 1 ;}
+	} || fail echo "failed to make go of $source"
diff --git a/make/make/go b/make/make/go
--- a/make/make/go
+++ b/make/make/go
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 function use_deps {
-	cd "$0" ;}
+	cd "$root/source/meta/make/make" ;}
 function use_coreutils {
 	if [[ `uname` == 'Darwin' ]]; then
 		[ -d "/usr/local/opt/coreutils/libexec/gnubin" ] || {
@@ -49,3 +49,51 @@ use_coreutils || {
 	pwd="$(pwd)"
 	root="$(find_project_root)"
 	temp="$root/temp" ;}
+function as_make {
+	if [ "$#" -ne 2 ]; then
+		echo "$(basename "$(dirname ${0})") <source> <out>"
+		exit 1 ;fi
+
+	_pwd="$(pwd)"
+	cd "$pwd"
+	source="$(readlink -m "${1%/}")"
+	out="$(readlink -m "${2%/}")"
+	cd "$_pwd" ;}
+
+make_defs=$(cat << 'EOF'
+function as_make {
+	if [ "$#" -ne 2 ]; then
+		echo "$(basename "$(dirname ${0})") <source> <out>"
+		exit 1 ;fi
+
+	_pwd="$(pwd)"
+	cd "$pwd"
+	source="$(readlink -m "${1%/}")"
+	out="$(readlink -m "${2%/}")"
+	cd "$_pwd" ;}
+EOF
+)
+
+use_deps && as_make $@ || {
+	echo "please compile $root/source/meta/make/make"
+	exit 1
+} && use_coreutils || (fail
+) && { 
+	_make="$(find_temp_path)"
+	mkdir "$_make"
+	rm "$_make/*" 2> /dev/null
+
+	cp "$source/go" "$_make/copy"
+	cp "$source/go" "$_make/_make"
+	> "$_make/_make"
+
+	cat "$source/go" | head -1 >> "$_make/_make"
+	echo "$make_defs" >> "$_make/_make"
+	cat "$source/go" | tail -n +2 >> "$_make/_make"
+
+	cp "$_make/_make" "$source/go"
+
+	"$root/make/go/go" "$source" "$out"
+
+	cp "$_make/copy" "$source/go"
+	} || fail echo "failed to make make"
diff --git a/make/ni/go b/make/ni/go
--- a/make/ni/go
+++ b/make/ni/go
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 function use_deps {
-	cd "$0" ;}
+	cd "$root/source/meta/make/ni" ;}
 function use_coreutils {
 	if [[ `uname` == 'Darwin' ]]; then
 		[ -d "/usr/local/opt/coreutils/libexec/gnubin" ] || {
@@ -49,3 +49,18 @@ use_coreutils || {
 	pwd="$(pwd)"
 	root="$(find_project_root)"
 	temp="$root/temp" ;}
+function as_make {
+	if [ "$#" -ne 2 ]; then
+		echo "$(basename "$(dirname ${0})") <source> <out>"
+		exit 1 ;fi
+
+	_pwd="$(pwd)"
+	cd "$pwd"
+	source="$(readlink -m "${1%/}")"
+	out="$(readlink -m "${2%/}")"
+	cd "$_pwd" ;}
+use_deps && as_make $@ || {
+	echo "please compile $root/source/meta/make/ni"
+	exit 1
+} && use_file "$source/go" || (fail
+) && "$root/make/go/go" "$source" "$out" || fail echo "failed to make ni"
diff --git a/source/meta/make/app/android/go b/source/meta/make/app/android/go
--- a/source/meta/make/app/android/go
+++ b/source/meta/make/app/android/go
@@ -1,14 +1,11 @@
 #!/usr/bin/env bash
-use_deps || {
+use_deps && as_make $@ || {
 	echo "please compile $0"
 	exit 1
-} && use_gnu_core_utils || {
-	exit 1
-} && use_node || {
-	exit 1
-} && use_file "$src" || {
-	exit 1
-} && {
+} && use_gnu_core_utils || (fail
+) && use_node || (fail
+) && use_file "$source" || (fail
+) && {
 	if [ -d "${package_root}/dist/cordova/android" ]; then
 		rm -r "${package_root}/dist/cordova/android" ;fi
 
@@ -33,7 +30,4 @@ use_deps || {
 	cordova-icon
 	#maybe no need www?
 	#zip -r cordova-android.zip config.xml www/ platforms/ plugins/
-	} || {
-	echo "failed to make app/android"
-	exit 1; }
-
+	} || fail echo "failed to make app/android"
diff --git a/source/meta/make/app/ios/go b/source/meta/make/app/ios/go
--- a/source/meta/make/app/ios/go
+++ b/source/meta/make/app/ios/go
@@ -1,14 +1,11 @@
 #!/usr/bin/env bash
-use_deps || {
+use_deps && as_make $@ || {
 	echo "please compile $0"
 	exit 1
-} && use_gnu_coreutils || {
-	exit 1
-} && use_node || {
-	exit 1
-} && use_file "$src" || {
-	exit 1
-} && {
+} && use_gnu_coreutils || (fail
+) && use_node || (fail
+) && use_file "$source" || (fail
+) && {
 	if [ -d "${package_root}/dist/cordova/ios" ]; then
 		rm -r "${package_root}/dist/cordova/ios" ;fi
 
@@ -33,6 +30,4 @@ use_deps || {
 	cordova-icon
 	#maybe no need www?
 	#zip -r cordova-ios.zip config.xml www/ platforms/ plugins/
-	} || {
-	echo "failed to make app/ios"
-	exit 1; }
+	} || fail echo "failed to make app/ios"
diff --git a/source/meta/make/go/go b/source/meta/make/go/go
--- a/source/meta/make/go/go
+++ b/source/meta/make/go/go
@@ -1,12 +1,10 @@
 #!/usr/bin/env bash
-use_deps || {
+use_deps && as_make $@ || {
 	echo "please compile $0"
 	exit 1 
-} && use_coreutils || {
-	exit 1 
-} && use_file "$source/go" || {
-	exit 1 
-} && {
+} && use_coreutils || (fail
+) && use_file "$source/go" || (fail
+) && {
 	mkdir -p "$out" && rm -r "$out/*" 2> /dev/null
 	cp "$source/go" "$out/go"
 
@@ -59,7 +57,7 @@ use_deps || {
 		elif [[ -n $forward_part ]]; then
 		    result="${forward_part:1}" ;fi
 
-		echo $result; }
+		echo $result ;}
 
 	source_from_root="$(rel_path "$root" "$source")"
 	source_rel_path='$root/'"$source_from_root"
@@ -68,6 +66,4 @@ use_deps || {
 
 	sed -i 's|$''0|'"$source_rel_path"'|g' "$out/go"
 
-	} || {
-	echo "failed to make go of $source"
-	exit 1 ;}
+	} || fail echo "failed to make go of $source"
diff --git a/source/meta/make/ui/build/assets/go b/source/meta/make/ui/build/assets/go
--- a/source/meta/make/ui/build/assets/go
+++ b/source/meta/make/ui/build/assets/go
@@ -1,11 +1,7 @@
 #!/usr/bin/env bash
-use_deps || {
+use_deps && as_make $@ || {
 	echo "please compile $0"
 	exit 1
-} && use_node || {
-	exit 1
-} && use_file "$src" || {
-	exit 1
-} && node "fn.js" || {
-	echo "failed to make build ui/assets"
-	exit 1; }
+} && use_node || (fail
+) && use_file "$source" || (fail
+) && node "fn.js" || fail echo "failed to make build ui/assets"
diff --git a/source/meta/make/ui/go b/source/meta/make/ui/go
--- a/source/meta/make/ui/go
+++ b/source/meta/make/ui/go
@@ -1,12 +1,10 @@
 #!/usr/bin/env bash
-use_deps || {
+use_deps && as_make $@ || {
 	echo "please compile $0"
 	exit 1
-} && use_node || {
-	exit 1
-} && use_file "$source" || {
-	exit 1
-} && time (
+} && use_node || (fail
+) && use_file "$source" || (fail
+) && time (
 	rm -r "$out" 2> /dev/null
 
 	(node "fn.js"
@@ -14,6 +12,4 @@ use_deps || {
 	) && (./build/styles/go
 	) && (./build/scripts/go
 	) && (./build/assets/go
-	) ) || {
-	echo "failed to make ui"
-	exit 1; }
+	) ) || fail echo "failed to make ui"
diff --git a/source/ni/go b/source/ni/go
--- a/source/ni/go
+++ b/source/ni/go
@@ -2,10 +2,7 @@
 use_deps || {
 	echo "please compile $0"
 	exit 1
-} && use_node || {
-	exit 1
-} && use_file "$src" || {
-	exit 1
-} && node "fn.js" || {
-	echo "failed to host ni"
-	exit 1; }
+} && use_node || (fail
+) && [ "$#" -eq 1 ] && {
+	webroot="$(readlink -f "$1")" ;} || (fail echo "please specify one webroot"
+) && node "fn.js" "$webroot" || fail echo "failed to host ni"
